# Generated by Django 4.2.28 on 2026-02-13 22:12

import core.models.vision_analysis
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('mileage_km', models.PositiveIntegerField(default=0)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='petrol', max_length=20)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('luxury', 'Luxury'), ('premium', 'Premium'), ('economic', 'Economic')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('original_price_jod', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('listing_price_jod', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Car Listing',
                'verbose_name_plural': 'Car Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('mileage_km', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('luxury', 'Luxury'), ('premium', 'Premium'), ('economic', 'Economic')], max_length=20)),
                ('original_price_jod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depreciated_price_jod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depreciation_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.vision_analysis.car_image_upload_path)),
                ('detected_make', models.CharField(blank=True, max_length=50)),
                ('detected_model', models.CharField(blank=True, max_length=100)),
                ('detected_year', models.CharField(blank=True, max_length=20)),
                ('condition_summary', models.TextField(blank=True)),
                ('raw_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vision Analysis',
                'verbose_name_plural': 'Vision Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
